//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteDataService.ServiceCategoria {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Produto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Loja))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Modelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Marca))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Categoria))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Produto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Loja))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Modelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Marca))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Categoria))]
    public partial class EntityObject : TesteDataService.ServiceCategoria.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/PecaDica.Modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Produto : TesteDataService.ServiceCategoria.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Categoria CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfCategoriaTOjbUMNd CategoriaReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Loja LojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfLojaTOjbUMNd LojaReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Modelo ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd ModeloReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Categoria Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfCategoriaTOjbUMNd CategoriaReference {
            get {
                return this.CategoriaReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaReferenceField, value) != true)) {
                    this.CategoriaReferenceField = value;
                    this.RaisePropertyChanged("CategoriaReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Loja Loja {
            get {
                return this.LojaField;
            }
            set {
                if ((object.ReferenceEquals(this.LojaField, value) != true)) {
                    this.LojaField = value;
                    this.RaisePropertyChanged("Loja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfLojaTOjbUMNd LojaReference {
            get {
                return this.LojaReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.LojaReferenceField, value) != true)) {
                    this.LojaReferenceField = value;
                    this.RaisePropertyChanged("LojaReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Modelo Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd ModeloReference {
            get {
                return this.ModeloReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloReferenceField, value) != true)) {
                    this.ModeloReferenceField = value;
                    this.RaisePropertyChanged("ModeloReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loja", Namespace="http://schemas.datacontract.org/2004/07/PecaDica.Modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Loja : TesteDataService.ServiceCategoria.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeUsuario {
            get {
                return this.NomeUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true)) {
                    this.NomeUsuarioField = value;
                    this.RaisePropertyChanged("NomeUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReference {
            get {
                return this.ProdutoReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoReferenceField, value) != true)) {
                    this.ProdutoReferenceField = value;
                    this.RaisePropertyChanged("ProdutoReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Modelo", Namespace="http://schemas.datacontract.org/2004/07/PecaDica.Modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Modelo : TesteDataService.ServiceCategoria.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Marca MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfMarcaTOjbUMNd MarcaReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ano {
            get {
                return this.AnoField;
            }
            set {
                if ((this.AnoField.Equals(value) != true)) {
                    this.AnoField = value;
                    this.RaisePropertyChanged("Ano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Marca Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfMarcaTOjbUMNd MarcaReference {
            get {
                return this.MarcaReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaReferenceField, value) != true)) {
                    this.MarcaReferenceField = value;
                    this.RaisePropertyChanged("MarcaReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReference {
            get {
                return this.ProdutoReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoReferenceField, value) != true)) {
                    this.ProdutoReferenceField = value;
                    this.RaisePropertyChanged("ProdutoReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marca", Namespace="http://schemas.datacontract.org/2004/07/PecaDica.Modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Marca : TesteDataService.ServiceCategoria.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Modelo ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd ModeloReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Modelo Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd ModeloReference {
            get {
                return this.ModeloReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloReferenceField, value) != true)) {
                    this.ModeloReferenceField = value;
                    this.RaisePropertyChanged("ModeloReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/PecaDica.Modelo", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Categoria : TesteDataService.ServiceCategoria.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.Produto ProdutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.Produto Produto {
            get {
                return this.ProdutoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoField, value) != true)) {
                    this.ProdutoField = value;
                    this.RaisePropertyChanged("Produto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd ProdutoReference {
            get {
                return this.ProdutoReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoReferenceField, value) != true)) {
                    this.ProdutoReferenceField = value;
                    this.RaisePropertyChanged("ProdutoReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfProdutoTOjbUMNd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfProdutoTOjbUMNd : TesteDataService.ServiceCategoria.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfCategoriaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfLojaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfMarcaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Categoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Produto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Loja))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Modelo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.Marca))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfCategoriaTOjbUMNd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfCategoriaTOjbUMNd : TesteDataService.ServiceCategoria.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfLojaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfMarcaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfCategoriaTOjbUMNd))]
    public partial class EntityReference : TesteDataService.ServiceCategoria.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TesteDataService.ServiceCategoria.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TesteDataService.ServiceCategoria.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfProdutoTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfLojaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfModeloTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfMarcaTOjbUMNd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TesteDataService.ServiceCategoria.EntityReferenceOfCategoriaTOjbUMNd))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfLojaTOjbUMNd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfLojaTOjbUMNd : TesteDataService.ServiceCategoria.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfModeloTOjbUMNd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfModeloTOjbUMNd : TesteDataService.ServiceCategoria.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfMarcaTOjbUMNd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfMarcaTOjbUMNd : TesteDataService.ServiceCategoria.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCategoria.ICategoriaService")]
    public interface ICategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Inserir", ReplyAction="http://tempuri.org/ICategoriaService/InserirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/InserirDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Inserir(TesteDataService.ServiceCategoria.Categoria item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Deletar", ReplyAction="http://tempuri.org/ICategoriaService/DeletarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/DeletarDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Deletar(TesteDataService.ServiceCategoria.Categoria item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Alterar", ReplyAction="http://tempuri.org/ICategoriaService/AlterarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/AlterarDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Alterar(TesteDataService.ServiceCategoria.Categoria item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaServiceChannel : TesteDataService.ServiceCategoria.ICategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaServiceClient : System.ServiceModel.ClientBase<TesteDataService.ServiceCategoria.ICategoriaService>, TesteDataService.ServiceCategoria.ICategoriaService {
        
        public CategoriaServiceClient() {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Inserir(TesteDataService.ServiceCategoria.Categoria item) {
            base.Channel.Inserir(item);
        }
        
        public void Deletar(TesteDataService.ServiceCategoria.Categoria item) {
            base.Channel.Deletar(item);
        }
        
        public void Alterar(TesteDataService.ServiceCategoria.Categoria item) {
            base.Channel.Alterar(item);
        }
    }
}
