//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteDataService.ServiceCategoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCategoria.ICategoriaService")]
    public interface ICategoriaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Inserir", ReplyAction="http://tempuri.org/ICategoriaService/InserirResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/InserirDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Inserir(PecaDicas.Contratos.Categoria item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Deletar", ReplyAction="http://tempuri.org/ICategoriaService/DeletarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/DeletarDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Deletar(PecaDicas.Contratos.Categoria item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoriaService/Alterar", ReplyAction="http://tempuri.org/ICategoriaService/AlterarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PecaDicas.Contratos.Common.DetalhamentoFalha), Action="http://tempuri.org/ICategoriaService/AlterarDetalhamentoFalhaFault", Name="DetalhamentoFalha", Namespace="http://schemas.datacontract.org/2004/07/PecaDicas.Contratos.Common")]
        void Alterar(PecaDicas.Contratos.Categoria item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoriaServiceChannel : TesteDataService.ServiceCategoria.ICategoriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoriaServiceClient : System.ServiceModel.ClientBase<TesteDataService.ServiceCategoria.ICategoriaService>, TesteDataService.ServiceCategoria.ICategoriaService {
        
        public CategoriaServiceClient() {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Inserir(PecaDicas.Contratos.Categoria item) {
            base.Channel.Inserir(item);
        }
        
        public void Deletar(PecaDicas.Contratos.Categoria item) {
            base.Channel.Deletar(item);
        }
        
        public void Alterar(PecaDicas.Contratos.Categoria item) {
            base.Channel.Alterar(item);
        }
    }
}
