//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 19/08/2013 21:26:27
namespace PecaDica.App.PecaDicaServicos
{
    
    /// <summary>
    /// There are no comments for PecaDicaBDEntities in the schema.
    /// </summary>
    public partial class PecaDicaBDEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PecaDicaBDEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PecaDicaBDEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("PecaDicaBDModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("PecaDica.App.PecaDicaServicos", typeName.Substring(15)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("PecaDica.App.PecaDicaServicos", global::System.StringComparison.Ordinal))
            {
                return string.Concat("PecaDicaBDModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Categoria in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Categoria> Categoria
        {
            get
            {
                if ((this._Categoria == null))
                {
                    this._Categoria = base.CreateQuery<Categoria>("Categoria");
                }
                return this._Categoria;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Categoria> _Categoria;
        /// <summary>
        /// There are no comments for Loja in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Loja> Loja
        {
            get
            {
                if ((this._Loja == null))
                {
                    this._Loja = base.CreateQuery<Loja>("Loja");
                }
                return this._Loja;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Loja> _Loja;
        /// <summary>
        /// There are no comments for Marca in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Marca> Marca
        {
            get
            {
                if ((this._Marca == null))
                {
                    this._Marca = base.CreateQuery<Marca>("Marca");
                }
                return this._Marca;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Marca> _Marca;
        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Modelo> Modelo
        {
            get
            {
                if ((this._Modelo == null))
                {
                    this._Modelo = base.CreateQuery<Modelo>("Modelo");
                }
                return this._Modelo;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Modelo> _Modelo;
        /// <summary>
        /// There are no comments for Produto in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Produto> Produto
        {
            get
            {
                if ((this._Produto == null))
                {
                    this._Produto = base.CreateQuery<Produto>("Produto");
                }
                return this._Produto;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Produto> _Produto;
        /// <summary>
        /// There are no comments for Categoria in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
        /// <summary>
        /// There are no comments for Loja in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLoja(Loja loja)
        {
            base.AddObject("Loja", loja);
        }
        /// <summary>
        /// There are no comments for Marca in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMarca(Marca marca)
        {
            base.AddObject("Marca", marca);
        }
        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToModelo(Modelo modelo)
        {
            base.AddObject("Modelo", modelo);
        }
        /// <summary>
        /// There are no comments for Produto in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }
    }
    /// <summary>
    /// There are no comments for PecaDicaBDModel.Categoria in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Categoria
    {
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="descricao">Initial value of Descricao.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Categoria CreateCategoria(global::System.Guid ID, string nome, string descricao)
        {
            Categoria categoria = new Categoria();
            categoria.Id = ID;
            categoria.Nome = nome;
            categoria.Descricao = descricao;
            return categoria;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property Descricao in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Descricao
        {
            get
            {
                return this._Descricao;
            }
            set
            {
                this.OnDescricaoChanging(value);
                this._Descricao = value;
                this.OnDescricaoChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Descricao;
        partial void OnDescricaoChanging(string value);
        partial void OnDescricaoChanged();
        /// <summary>
        /// There are no comments for Produto in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Produto Produto
        {
            get
            {
                return this._Produto;
            }
            set
            {
                this._Produto = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Produto _Produto;
    }
    /// <summary>
    /// There are no comments for PecaDicaBDModel.Loja in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Loja
    {
        /// <summary>
        /// Create a new Loja object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="email">Initial value of Email.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="nomeUsuario">Initial value of NomeUsuario.</param>
        /// <param name="senha">Initial value of Senha.</param>
        /// <param name="endereco">Initial value of Endereco.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Loja CreateLoja(global::System.Guid ID, string email, string nome, string nomeUsuario, string senha, string endereco)
        {
            Loja loja = new Loja();
            loja.Id = ID;
            loja.Email = email;
            loja.Nome = nome;
            loja.NomeUsuario = nomeUsuario;
            loja.Senha = senha;
            loja.Endereco = endereco;
            return loja;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property NomeUsuario in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NomeUsuario
        {
            get
            {
                return this._NomeUsuario;
            }
            set
            {
                this.OnNomeUsuarioChanging(value);
                this._NomeUsuario = value;
                this.OnNomeUsuarioChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NomeUsuario;
        partial void OnNomeUsuarioChanging(string value);
        partial void OnNomeUsuarioChanged();
        /// <summary>
        /// There are no comments for Property Senha in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Senha
        {
            get
            {
                return this._Senha;
            }
            set
            {
                this.OnSenhaChanging(value);
                this._Senha = value;
                this.OnSenhaChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Senha;
        partial void OnSenhaChanging(string value);
        partial void OnSenhaChanged();
        /// <summary>
        /// There are no comments for Property Endereco in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Endereco
        {
            get
            {
                return this._Endereco;
            }
            set
            {
                this.OnEnderecoChanging(value);
                this._Endereco = value;
                this.OnEnderecoChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Endereco;
        partial void OnEnderecoChanging(string value);
        partial void OnEnderecoChanged();
        /// <summary>
        /// There are no comments for Produto in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Produto Produto
        {
            get
            {
                return this._Produto;
            }
            set
            {
                this._Produto = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Produto _Produto;
    }
    /// <summary>
    /// There are no comments for PecaDicaBDModel.Marca in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Marca
    {
        /// <summary>
        /// Create a new Marca object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nome">Initial value of Nome.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Marca CreateMarca(global::System.Guid ID, string nome)
        {
            Marca marca = new Marca();
            marca.Id = ID;
            marca.Nome = nome;
            return marca;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Modelo Modelo
        {
            get
            {
                return this._Modelo;
            }
            set
            {
                this._Modelo = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Modelo _Modelo;
    }
    /// <summary>
    /// There are no comments for PecaDicaBDModel.Modelo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Modelo
    {
        /// <summary>
        /// Create a new Modelo object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nome">Initial value of Nome.</param>
        /// <param name="ano">Initial value of Ano.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Modelo CreateModelo(global::System.Guid ID, string nome, int ano)
        {
            Modelo modelo = new Modelo();
            modelo.Id = ID;
            modelo.Nome = nome;
            modelo.Ano = ano;
            return modelo;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Property Ano in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Ano
        {
            get
            {
                return this._Ano;
            }
            set
            {
                this.OnAnoChanging(value);
                this._Ano = value;
                this.OnAnoChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Ano;
        partial void OnAnoChanging(int value);
        partial void OnAnoChanged();
        /// <summary>
        /// There are no comments for Marca in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Marca Marca
        {
            get
            {
                return this._Marca;
            }
            set
            {
                this._Marca = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Marca _Marca;
        /// <summary>
        /// There are no comments for Produto in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Produto Produto
        {
            get
            {
                return this._Produto;
            }
            set
            {
                this._Produto = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Produto _Produto;
    }
    /// <summary>
    /// There are no comments for PecaDicaBDModel.Produto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Produto
    {
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="nome">Initial value of Nome.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Produto CreateProduto(global::System.Guid ID, string nome)
        {
            Produto produto = new Produto();
            produto.Id = ID;
            produto.Nome = nome;
            return produto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Nome in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Nome
        {
            get
            {
                return this._Nome;
            }
            set
            {
                this.OnNomeChanging(value);
                this._Nome = value;
                this.OnNomeChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Nome;
        partial void OnNomeChanging(string value);
        partial void OnNomeChanged();
        /// <summary>
        /// There are no comments for Categoria in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Categoria Categoria
        {
            get
            {
                return this._Categoria;
            }
            set
            {
                this._Categoria = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Categoria _Categoria;
        /// <summary>
        /// There are no comments for Loja in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Loja Loja
        {
            get
            {
                return this._Loja;
            }
            set
            {
                this._Loja = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Loja _Loja;
        /// <summary>
        /// There are no comments for Modelo in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Modelo Modelo
        {
            get
            {
                return this._Modelo;
            }
            set
            {
                this._Modelo = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Modelo _Modelo;
    }
}
