//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("pecaDicaBDModel", "FK_Produto_Categoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PecaDicas.Services.DataServices.Categoria), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PecaDicas.Services.DataServices.Produto), true)]
[assembly: EdmRelationshipAttribute("pecaDicaBDModel", "FK_Produto_Loja", "Loja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PecaDicas.Services.DataServices.Loja), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PecaDicas.Services.DataServices.Produto), true)]
[assembly: EdmRelationshipAttribute("pecaDicaBDModel", "FK_Modelo_Marca", "Marca", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PecaDicas.Services.DataServices.Marca), "Modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PecaDicas.Services.DataServices.Modelo), true)]
[assembly: EdmRelationshipAttribute("pecaDicaBDModel", "FK_Produto_Modelo", "Modelo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PecaDicas.Services.DataServices.Modelo), "Produto", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PecaDicas.Services.DataServices.Produto), true)]

#endregion

namespace PecaDicas.Services.DataServices
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pecaDicaBDEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pecaDicaBDEntities object using the connection string found in the 'pecaDicaBDEntities' section of the application configuration file.
        /// </summary>
        public pecaDicaBDEntities() : base("name=pecaDicaBDEntities", "pecaDicaBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pecaDicaBDEntities object.
        /// </summary>
        public pecaDicaBDEntities(string connectionString) : base(connectionString, "pecaDicaBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pecaDicaBDEntities object.
        /// </summary>
        public pecaDicaBDEntities(EntityConnection connection) : base(connection, "pecaDicaBDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categoria
        {
            get
            {
                if ((_Categoria == null))
                {
                    _Categoria = base.CreateObjectSet<Categoria>("Categoria");
                }
                return _Categoria;
            }
        }
        private ObjectSet<Categoria> _Categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Loja> Loja
        {
            get
            {
                if ((_Loja == null))
                {
                    _Loja = base.CreateObjectSet<Loja>("Loja");
                }
                return _Loja;
            }
        }
        private ObjectSet<Loja> _Loja;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Marca> Marca
        {
            get
            {
                if ((_Marca == null))
                {
                    _Marca = base.CreateObjectSet<Marca>("Marca");
                }
                return _Marca;
            }
        }
        private ObjectSet<Marca> _Marca;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modelo> Modelo
        {
            get
            {
                if ((_Modelo == null))
                {
                    _Modelo = base.CreateObjectSet<Modelo>("Modelo");
                }
                return _Modelo;
            }
        }
        private ObjectSet<Modelo> _Modelo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Produto> Produto
        {
            get
            {
                if ((_Produto == null))
                {
                    _Produto = base.CreateObjectSet<Produto>("Produto");
                }
                return _Produto;
            }
        }
        private ObjectSet<Produto> _Produto;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Loja EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoja(Loja loja)
        {
            base.AddObject("Loja", loja);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Marca EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarca(Marca marca)
        {
            base.AddObject("Marca", marca);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modelo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModelo(Modelo modelo)
        {
            base.AddObject("Modelo", modelo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Produto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProduto(Produto produto)
        {
            base.AddObject("Produto", produto);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pecaDicaBDModel", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="descricao">Initial value of the Descricao property.</param>
        public static Categoria CreateCategoria(global::System.Guid id, global::System.String nome, global::System.String descricao)
        {
            Categoria categoria = new Categoria();
            categoria.Id = id;
            categoria.Nome = nome;
            categoria.Descricao = descricao;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Categoria", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Categoria", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Categoria", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Categoria", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Categoria", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pecaDicaBDModel", Name="Loja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Loja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Loja object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="nomeUsuario">Initial value of the NomeUsuario property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="endereco">Initial value of the Endereco property.</param>
        public static Loja CreateLoja(global::System.Guid id, global::System.String email, global::System.String nome, global::System.String nomeUsuario, global::System.String senha, global::System.String endereco)
        {
            Loja loja = new Loja();
            loja.Id = id;
            loja.Email = email;
            loja.Nome = nome;
            loja.NomeUsuario = nomeUsuario;
            loja.Senha = senha;
            loja.Endereco = endereco;
            return loja;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomeUsuario
        {
            get
            {
                return _NomeUsuario;
            }
            set
            {
                OnNomeUsuarioChanging(value);
                ReportPropertyChanging("NomeUsuario");
                _NomeUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomeUsuario");
                OnNomeUsuarioChanged();
            }
        }
        private global::System.String _NomeUsuario;
        partial void OnNomeUsuarioChanging(global::System.String value);
        partial void OnNomeUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Endereco
        {
            get
            {
                return _Endereco;
            }
            set
            {
                OnEnderecoChanging(value);
                ReportPropertyChanging("Endereco");
                _Endereco = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Endereco");
                OnEnderecoChanged();
            }
        }
        private global::System.String _Endereco;
        partial void OnEnderecoChanging(global::System.String value);
        partial void OnEnderecoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Loja", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Loja", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Loja", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Loja", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Loja", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pecaDicaBDModel", Name="Marca")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Marca : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Marca object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Marca CreateMarca(global::System.Guid id, global::System.String nome)
        {
            Marca marca = new Marca();
            marca.Id = id;
            marca.Nome = nome;
            return marca;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Modelo_Marca", "Modelo")]
        public Modelo Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Modelo_Marca", "Modelo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Modelo_Marca", "Modelo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modelo> ModeloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Modelo_Marca", "Modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modelo>("pecaDicaBDModel.FK_Modelo_Marca", "Modelo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pecaDicaBDModel", Name="Modelo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modelo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modelo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="ano">Initial value of the Ano property.</param>
        public static Modelo CreateModelo(global::System.Guid id, global::System.String nome, global::System.Int32 ano)
        {
            Modelo modelo = new Modelo();
            modelo.Id = id;
            modelo.Nome = nome;
            modelo.Ano = ano;
            return modelo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ano
        {
            get
            {
                return _Ano;
            }
            set
            {
                OnAnoChanging(value);
                ReportPropertyChanging("Ano");
                _Ano = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ano");
                OnAnoChanged();
            }
        }
        private global::System.Int32 _Ano;
        partial void OnAnoChanging(global::System.Int32 value);
        partial void OnAnoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Modelo_Marca", "Marca")]
        public Marca Marca
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("pecaDicaBDModel.FK_Modelo_Marca", "Marca").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("pecaDicaBDModel.FK_Modelo_Marca", "Marca").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Marca> MarcaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Marca>("pecaDicaBDModel.FK_Modelo_Marca", "Marca");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Marca>("pecaDicaBDModel.FK_Modelo_Marca", "Marca", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Modelo", "Produto")]
        public Produto Produto
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Modelo", "Produto").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Modelo", "Produto").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Produto> ProdutoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Modelo", "Produto");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Produto>("pecaDicaBDModel.FK_Produto_Modelo", "Produto", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pecaDicaBDModel", Name="Produto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Produto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Produto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Produto CreateProduto(global::System.Guid id, global::System.String nome)
        {
            Produto produto = new Produto();
            produto.Id = id;
            produto.Nome = nome;
            return produto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Categoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("pecaDicaBDModel.FK_Produto_Categoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("pecaDicaBDModel.FK_Produto_Categoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("pecaDicaBDModel.FK_Produto_Categoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("pecaDicaBDModel.FK_Produto_Categoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Loja", "Loja")]
        public Loja Loja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("pecaDicaBDModel.FK_Produto_Loja", "Loja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("pecaDicaBDModel.FK_Produto_Loja", "Loja").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Loja> LojaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Loja>("pecaDicaBDModel.FK_Produto_Loja", "Loja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Loja>("pecaDicaBDModel.FK_Produto_Loja", "Loja", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("pecaDicaBDModel", "FK_Produto_Modelo", "Modelo")]
        public Modelo Modelo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Produto_Modelo", "Modelo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Produto_Modelo", "Modelo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modelo> ModeloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modelo>("pecaDicaBDModel.FK_Produto_Modelo", "Modelo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modelo>("pecaDicaBDModel.FK_Produto_Modelo", "Modelo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
